// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginResponseMessage.proto

package com.example.laser.message;

public final class LoginResponseMessageFactory {
  private LoginResponseMessageFactory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginResponseMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .message.ResponseCmdHeader respCmdHeader = 1;
    /**
     * <code>required .message.ResponseCmdHeader respCmdHeader = 1;</code>
     */
    boolean hasRespCmdHeader();
    /**
     * <code>required .message.ResponseCmdHeader respCmdHeader = 1;</code>
     */
    com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader getRespCmdHeader();
    /**
     * <code>required .message.ResponseCmdHeader respCmdHeader = 1;</code>
     */
    com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeaderOrBuilder getRespCmdHeaderOrBuilder();

    // required string clientID = 2;
    /**
     * <code>required string clientID = 2;</code>
     */
    boolean hasClientID();
    /**
     * <code>required string clientID = 2;</code>
     */
    java.lang.String getClientID();
    /**
     * <code>required string clientID = 2;</code>
     */
    com.google.protobuf.ByteString
        getClientIDBytes();
  }
  /**
   * Protobuf type {@code message.LoginResponseMessage}
   */
  public static final class LoginResponseMessage extends
      com.google.protobuf.GeneratedMessage
      implements LoginResponseMessageOrBuilder {
    // Use LoginResponseMessage.newBuilder() to construct.
    private LoginResponseMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginResponseMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginResponseMessage defaultInstance;
    public static LoginResponseMessage getDefaultInstance() {
      return defaultInstance;
    }

    public LoginResponseMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = respCmdHeader_.toBuilder();
              }
              respCmdHeader_ = input.readMessage(com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(respCmdHeader_);
                respCmdHeader_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              clientID_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.laser.message.LoginResponseMessageFactory.internal_static_message_LoginResponseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.laser.message.LoginResponseMessageFactory.internal_static_message_LoginResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage.class, com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginResponseMessage> PARSER =
        new com.google.protobuf.AbstractParser<LoginResponseMessage>() {
      public LoginResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginResponseMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResponseMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .message.ResponseCmdHeader respCmdHeader = 1;
    public static final int RESPCMDHEADER_FIELD_NUMBER = 1;
    private com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader respCmdHeader_;
    /**
     * <code>required .message.ResponseCmdHeader respCmdHeader = 1;</code>
     */
    public boolean hasRespCmdHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .message.ResponseCmdHeader respCmdHeader = 1;</code>
     */
    public com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader getRespCmdHeader() {
      return respCmdHeader_;
    }
    /**
     * <code>required .message.ResponseCmdHeader respCmdHeader = 1;</code>
     */
    public com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeaderOrBuilder getRespCmdHeaderOrBuilder() {
      return respCmdHeader_;
    }

    // required string clientID = 2;
    public static final int CLIENTID_FIELD_NUMBER = 2;
    private java.lang.Object clientID_;
    /**
     * <code>required string clientID = 2;</code>
     */
    public boolean hasClientID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string clientID = 2;</code>
     */
    public java.lang.String getClientID() {
      java.lang.Object ref = clientID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string clientID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientIDBytes() {
      java.lang.Object ref = clientID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      respCmdHeader_ = com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.getDefaultInstance();
      clientID_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRespCmdHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getRespCmdHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, respCmdHeader_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getClientIDBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, respCmdHeader_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getClientIDBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.LoginResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.laser.message.LoginResponseMessageFactory.internal_static_message_LoginResponseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.laser.message.LoginResponseMessageFactory.internal_static_message_LoginResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage.class, com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage.Builder.class);
      }

      // Construct using com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRespCmdHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (respCmdHeaderBuilder_ == null) {
          respCmdHeader_ = com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.getDefaultInstance();
        } else {
          respCmdHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        clientID_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.laser.message.LoginResponseMessageFactory.internal_static_message_LoginResponseMessage_descriptor;
      }

      public com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage getDefaultInstanceForType() {
        return com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage.getDefaultInstance();
      }

      public com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage build() {
        com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage buildPartial() {
        com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage result = new com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (respCmdHeaderBuilder_ == null) {
          result.respCmdHeader_ = respCmdHeader_;
        } else {
          result.respCmdHeader_ = respCmdHeaderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientID_ = clientID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage) {
          return mergeFrom((com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage other) {
        if (other == com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage.getDefaultInstance()) return this;
        if (other.hasRespCmdHeader()) {
          mergeRespCmdHeader(other.getRespCmdHeader());
        }
        if (other.hasClientID()) {
          bitField0_ |= 0x00000002;
          clientID_ = other.clientID_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRespCmdHeader()) {
          
          return false;
        }
        if (!hasClientID()) {
          
          return false;
        }
        if (!getRespCmdHeader().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.laser.message.LoginResponseMessageFactory.LoginResponseMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .message.ResponseCmdHeader respCmdHeader = 1;
      private com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader respCmdHeader_ = com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader, com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.Builder, com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeaderOrBuilder> respCmdHeaderBuilder_;
      /**
       * <code>required .message.ResponseCmdHeader respCmdHeader = 1;</code>
       */
      public boolean hasRespCmdHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .message.ResponseCmdHeader respCmdHeader = 1;</code>
       */
      public com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader getRespCmdHeader() {
        if (respCmdHeaderBuilder_ == null) {
          return respCmdHeader_;
        } else {
          return respCmdHeaderBuilder_.getMessage();
        }
      }
      /**
       * <code>required .message.ResponseCmdHeader respCmdHeader = 1;</code>
       */
      public Builder setRespCmdHeader(com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader value) {
        if (respCmdHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          respCmdHeader_ = value;
          onChanged();
        } else {
          respCmdHeaderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .message.ResponseCmdHeader respCmdHeader = 1;</code>
       */
      public Builder setRespCmdHeader(
          com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.Builder builderForValue) {
        if (respCmdHeaderBuilder_ == null) {
          respCmdHeader_ = builderForValue.build();
          onChanged();
        } else {
          respCmdHeaderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .message.ResponseCmdHeader respCmdHeader = 1;</code>
       */
      public Builder mergeRespCmdHeader(com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader value) {
        if (respCmdHeaderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              respCmdHeader_ != com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.getDefaultInstance()) {
            respCmdHeader_ =
              com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.newBuilder(respCmdHeader_).mergeFrom(value).buildPartial();
          } else {
            respCmdHeader_ = value;
          }
          onChanged();
        } else {
          respCmdHeaderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .message.ResponseCmdHeader respCmdHeader = 1;</code>
       */
      public Builder clearRespCmdHeader() {
        if (respCmdHeaderBuilder_ == null) {
          respCmdHeader_ = com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.getDefaultInstance();
          onChanged();
        } else {
          respCmdHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .message.ResponseCmdHeader respCmdHeader = 1;</code>
       */
      public com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.Builder getRespCmdHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRespCmdHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .message.ResponseCmdHeader respCmdHeader = 1;</code>
       */
      public com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeaderOrBuilder getRespCmdHeaderOrBuilder() {
        if (respCmdHeaderBuilder_ != null) {
          return respCmdHeaderBuilder_.getMessageOrBuilder();
        } else {
          return respCmdHeader_;
        }
      }
      /**
       * <code>required .message.ResponseCmdHeader respCmdHeader = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader, com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.Builder, com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeaderOrBuilder> 
          getRespCmdHeaderFieldBuilder() {
        if (respCmdHeaderBuilder_ == null) {
          respCmdHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader, com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.Builder, com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeaderOrBuilder>(
                  respCmdHeader_,
                  getParentForChildren(),
                  isClean());
          respCmdHeader_ = null;
        }
        return respCmdHeaderBuilder_;
      }

      // required string clientID = 2;
      private java.lang.Object clientID_ = "";
      /**
       * <code>required string clientID = 2;</code>
       */
      public boolean hasClientID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string clientID = 2;</code>
       */
      public java.lang.String getClientID() {
        java.lang.Object ref = clientID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clientID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string clientID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClientIDBytes() {
        java.lang.Object ref = clientID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string clientID = 2;</code>
       */
      public Builder setClientID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string clientID = 2;</code>
       */
      public Builder clearClientID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientID_ = getDefaultInstance().getClientID();
        onChanged();
        return this;
      }
      /**
       * <code>required string clientID = 2;</code>
       */
      public Builder setClientIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientID_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:message.LoginResponseMessage)
    }

    static {
      defaultInstance = new LoginResponseMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:message.LoginResponseMessage)
  }

  public interface ResponseCmdHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 resultcode = 1;
    /**
     * <code>required int32 resultcode = 1;</code>
     */
    boolean hasResultcode();
    /**
     * <code>required int32 resultcode = 1;</code>
     */
    int getResultcode();

    // required string desc = 2;
    /**
     * <code>required string desc = 2;</code>
     */
    boolean hasDesc();
    /**
     * <code>required string desc = 2;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>required string desc = 2;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();
  }
  /**
   * Protobuf type {@code message.ResponseCmdHeader}
   */
  public static final class ResponseCmdHeader extends
      com.google.protobuf.GeneratedMessage
      implements ResponseCmdHeaderOrBuilder {
    // Use ResponseCmdHeader.newBuilder() to construct.
    private ResponseCmdHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResponseCmdHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResponseCmdHeader defaultInstance;
    public static ResponseCmdHeader getDefaultInstance() {
      return defaultInstance;
    }

    public ResponseCmdHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseCmdHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              resultcode_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              desc_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.laser.message.LoginResponseMessageFactory.internal_static_message_ResponseCmdHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.laser.message.LoginResponseMessageFactory.internal_static_message_ResponseCmdHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.class, com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<ResponseCmdHeader> PARSER =
        new com.google.protobuf.AbstractParser<ResponseCmdHeader>() {
      public ResponseCmdHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseCmdHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseCmdHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 resultcode = 1;
    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private int resultcode_;
    /**
     * <code>required int32 resultcode = 1;</code>
     */
    public boolean hasResultcode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 resultcode = 1;</code>
     */
    public int getResultcode() {
      return resultcode_;
    }

    // required string desc = 2;
    public static final int DESC_FIELD_NUMBER = 2;
    private java.lang.Object desc_;
    /**
     * <code>required string desc = 2;</code>
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string desc = 2;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          desc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string desc = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      resultcode_ = 0;
      desc_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResultcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDesc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, resultcode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDescBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, resultcode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDescBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.ResponseCmdHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.laser.message.LoginResponseMessageFactory.internal_static_message_ResponseCmdHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.laser.message.LoginResponseMessageFactory.internal_static_message_ResponseCmdHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.class, com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.Builder.class);
      }

      // Construct using com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultcode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.laser.message.LoginResponseMessageFactory.internal_static_message_ResponseCmdHeader_descriptor;
      }

      public com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader getDefaultInstanceForType() {
        return com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.getDefaultInstance();
      }

      public com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader build() {
        com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader buildPartial() {
        com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader result = new com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultcode_ = resultcode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.desc_ = desc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader) {
          return mergeFrom((com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader other) {
        if (other == com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader.getDefaultInstance()) return this;
        if (other.hasResultcode()) {
          setResultcode(other.getResultcode());
        }
        if (other.hasDesc()) {
          bitField0_ |= 0x00000002;
          desc_ = other.desc_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultcode()) {
          
          return false;
        }
        if (!hasDesc()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.laser.message.LoginResponseMessageFactory.ResponseCmdHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 resultcode = 1;
      private int resultcode_ ;
      /**
       * <code>required int32 resultcode = 1;</code>
       */
      public boolean hasResultcode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 resultcode = 1;</code>
       */
      public int getResultcode() {
        return resultcode_;
      }
      /**
       * <code>required int32 resultcode = 1;</code>
       */
      public Builder setResultcode(int value) {
        bitField0_ |= 0x00000001;
        resultcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 resultcode = 1;</code>
       */
      public Builder clearResultcode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultcode_ = 0;
        onChanged();
        return this;
      }

      // required string desc = 2;
      private java.lang.Object desc_ = "";
      /**
       * <code>required string desc = 2;</code>
       */
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string desc = 2;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string desc = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string desc = 2;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string desc = 2;</code>
       */
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>required string desc = 2;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        desc_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:message.ResponseCmdHeader)
    }

    static {
      defaultInstance = new ResponseCmdHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:message.ResponseCmdHeader)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_message_LoginResponseMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_LoginResponseMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_message_ResponseCmdHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_ResponseCmdHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032LoginResponseMessage.proto\022\007message\"[\n" +
      "\024LoginResponseMessage\0221\n\rrespCmdHeader\030\001" +
      " \002(\0132\032.message.ResponseCmdHeader\022\020\n\010clie" +
      "ntID\030\002 \002(\t\"5\n\021ResponseCmdHeader\022\022\n\nresul" +
      "tcode\030\001 \002(\005\022\014\n\004desc\030\002 \002(\tB8\n\031com.example" +
      ".laser.messageB\033LoginResponseMessageFact" +
      "ory"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_message_LoginResponseMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_message_LoginResponseMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_message_LoginResponseMessage_descriptor,
              new java.lang.String[] { "RespCmdHeader", "ClientID", });
          internal_static_message_ResponseCmdHeader_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_message_ResponseCmdHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_message_ResponseCmdHeader_descriptor,
              new java.lang.String[] { "Resultcode", "Desc", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
