// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushBulkMeasureMessage.proto

package com.example.laser.message;

public final class PushBulkMeasureMessageFactory {
  private PushBulkMeasureMessageFactory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PushBulkMeasureMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .message.MeasureRecord measureLst = 1;
    /**
     * <code>repeated .message.MeasureRecord measureLst = 1;</code>
     */
    java.util.List<com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord> 
        getMeasureLstList();
    /**
     * <code>repeated .message.MeasureRecord measureLst = 1;</code>
     */
    com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord getMeasureLst(int index);
    /**
     * <code>repeated .message.MeasureRecord measureLst = 1;</code>
     */
    int getMeasureLstCount();
    /**
     * <code>repeated .message.MeasureRecord measureLst = 1;</code>
     */
    java.util.List<? extends com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecordOrBuilder> 
        getMeasureLstOrBuilderList();
    /**
     * <code>repeated .message.MeasureRecord measureLst = 1;</code>
     */
    com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecordOrBuilder getMeasureLstOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code message.PushBulkMeasureMessage}
   */
  public static final class PushBulkMeasureMessage extends
      com.google.protobuf.GeneratedMessage
      implements PushBulkMeasureMessageOrBuilder {
    // Use PushBulkMeasureMessage.newBuilder() to construct.
    private PushBulkMeasureMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PushBulkMeasureMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PushBulkMeasureMessage defaultInstance;
    public static PushBulkMeasureMessage getDefaultInstance() {
      return defaultInstance;
    }

    public PushBulkMeasureMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PushBulkMeasureMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                measureLst_ = new java.util.ArrayList<com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord>();
                mutable_bitField0_ |= 0x00000001;
              }
              measureLst_.add(input.readMessage(com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          measureLst_ = java.util.Collections.unmodifiableList(measureLst_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.laser.message.PushBulkMeasureMessageFactory.internal_static_message_PushBulkMeasureMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.laser.message.PushBulkMeasureMessageFactory.internal_static_message_PushBulkMeasureMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage.class, com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<PushBulkMeasureMessage> PARSER =
        new com.google.protobuf.AbstractParser<PushBulkMeasureMessage>() {
      public PushBulkMeasureMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PushBulkMeasureMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PushBulkMeasureMessage> getParserForType() {
      return PARSER;
    }

    // repeated .message.MeasureRecord measureLst = 1;
    public static final int MEASURELST_FIELD_NUMBER = 1;
    private java.util.List<com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord> measureLst_;
    /**
     * <code>repeated .message.MeasureRecord measureLst = 1;</code>
     */
    public java.util.List<com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord> getMeasureLstList() {
      return measureLst_;
    }
    /**
     * <code>repeated .message.MeasureRecord measureLst = 1;</code>
     */
    public java.util.List<? extends com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecordOrBuilder> 
        getMeasureLstOrBuilderList() {
      return measureLst_;
    }
    /**
     * <code>repeated .message.MeasureRecord measureLst = 1;</code>
     */
    public int getMeasureLstCount() {
      return measureLst_.size();
    }
    /**
     * <code>repeated .message.MeasureRecord measureLst = 1;</code>
     */
    public com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord getMeasureLst(int index) {
      return measureLst_.get(index);
    }
    /**
     * <code>repeated .message.MeasureRecord measureLst = 1;</code>
     */
    public com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecordOrBuilder getMeasureLstOrBuilder(
        int index) {
      return measureLst_.get(index);
    }

    private void initFields() {
      measureLst_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getMeasureLstCount(); i++) {
        if (!getMeasureLst(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < measureLst_.size(); i++) {
        output.writeMessage(1, measureLst_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < measureLst_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, measureLst_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.PushBulkMeasureMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.laser.message.PushBulkMeasureMessageFactory.internal_static_message_PushBulkMeasureMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.laser.message.PushBulkMeasureMessageFactory.internal_static_message_PushBulkMeasureMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage.class, com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage.Builder.class);
      }

      // Construct using com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMeasureLstFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (measureLstBuilder_ == null) {
          measureLst_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          measureLstBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.laser.message.PushBulkMeasureMessageFactory.internal_static_message_PushBulkMeasureMessage_descriptor;
      }

      public com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage getDefaultInstanceForType() {
        return com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage.getDefaultInstance();
      }

      public com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage build() {
        com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage buildPartial() {
        com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage result = new com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage(this);
        int from_bitField0_ = bitField0_;
        if (measureLstBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            measureLst_ = java.util.Collections.unmodifiableList(measureLst_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.measureLst_ = measureLst_;
        } else {
          result.measureLst_ = measureLstBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage) {
          return mergeFrom((com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage other) {
        if (other == com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage.getDefaultInstance()) return this;
        if (measureLstBuilder_ == null) {
          if (!other.measureLst_.isEmpty()) {
            if (measureLst_.isEmpty()) {
              measureLst_ = other.measureLst_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMeasureLstIsMutable();
              measureLst_.addAll(other.measureLst_);
            }
            onChanged();
          }
        } else {
          if (!other.measureLst_.isEmpty()) {
            if (measureLstBuilder_.isEmpty()) {
              measureLstBuilder_.dispose();
              measureLstBuilder_ = null;
              measureLst_ = other.measureLst_;
              bitField0_ = (bitField0_ & ~0x00000001);
              measureLstBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMeasureLstFieldBuilder() : null;
            } else {
              measureLstBuilder_.addAllMessages(other.measureLst_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getMeasureLstCount(); i++) {
          if (!getMeasureLst(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.laser.message.PushBulkMeasureMessageFactory.PushBulkMeasureMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .message.MeasureRecord measureLst = 1;
      private java.util.List<com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord> measureLst_ =
        java.util.Collections.emptyList();
      private void ensureMeasureLstIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          measureLst_ = new java.util.ArrayList<com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord>(measureLst_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord, com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.Builder, com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecordOrBuilder> measureLstBuilder_;

      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public java.util.List<com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord> getMeasureLstList() {
        if (measureLstBuilder_ == null) {
          return java.util.Collections.unmodifiableList(measureLst_);
        } else {
          return measureLstBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public int getMeasureLstCount() {
        if (measureLstBuilder_ == null) {
          return measureLst_.size();
        } else {
          return measureLstBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord getMeasureLst(int index) {
        if (measureLstBuilder_ == null) {
          return measureLst_.get(index);
        } else {
          return measureLstBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public Builder setMeasureLst(
          int index, com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord value) {
        if (measureLstBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeasureLstIsMutable();
          measureLst_.set(index, value);
          onChanged();
        } else {
          measureLstBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public Builder setMeasureLst(
          int index, com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.Builder builderForValue) {
        if (measureLstBuilder_ == null) {
          ensureMeasureLstIsMutable();
          measureLst_.set(index, builderForValue.build());
          onChanged();
        } else {
          measureLstBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public Builder addMeasureLst(com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord value) {
        if (measureLstBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeasureLstIsMutable();
          measureLst_.add(value);
          onChanged();
        } else {
          measureLstBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public Builder addMeasureLst(
          int index, com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord value) {
        if (measureLstBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeasureLstIsMutable();
          measureLst_.add(index, value);
          onChanged();
        } else {
          measureLstBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public Builder addMeasureLst(
          com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.Builder builderForValue) {
        if (measureLstBuilder_ == null) {
          ensureMeasureLstIsMutable();
          measureLst_.add(builderForValue.build());
          onChanged();
        } else {
          measureLstBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public Builder addMeasureLst(
          int index, com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.Builder builderForValue) {
        if (measureLstBuilder_ == null) {
          ensureMeasureLstIsMutable();
          measureLst_.add(index, builderForValue.build());
          onChanged();
        } else {
          measureLstBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public Builder addAllMeasureLst(
          java.lang.Iterable<? extends com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord> values) {
        if (measureLstBuilder_ == null) {
          ensureMeasureLstIsMutable();
          super.addAll(values, measureLst_);
          onChanged();
        } else {
          measureLstBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public Builder clearMeasureLst() {
        if (measureLstBuilder_ == null) {
          measureLst_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          measureLstBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public Builder removeMeasureLst(int index) {
        if (measureLstBuilder_ == null) {
          ensureMeasureLstIsMutable();
          measureLst_.remove(index);
          onChanged();
        } else {
          measureLstBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.Builder getMeasureLstBuilder(
          int index) {
        return getMeasureLstFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecordOrBuilder getMeasureLstOrBuilder(
          int index) {
        if (measureLstBuilder_ == null) {
          return measureLst_.get(index);  } else {
          return measureLstBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public java.util.List<? extends com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecordOrBuilder> 
           getMeasureLstOrBuilderList() {
        if (measureLstBuilder_ != null) {
          return measureLstBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(measureLst_);
        }
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.Builder addMeasureLstBuilder() {
        return getMeasureLstFieldBuilder().addBuilder(
            com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.Builder addMeasureLstBuilder(
          int index) {
        return getMeasureLstFieldBuilder().addBuilder(
            index, com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .message.MeasureRecord measureLst = 1;</code>
       */
      public java.util.List<com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.Builder> 
           getMeasureLstBuilderList() {
        return getMeasureLstFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord, com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.Builder, com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecordOrBuilder> 
          getMeasureLstFieldBuilder() {
        if (measureLstBuilder_ == null) {
          measureLstBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord, com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.Builder, com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecordOrBuilder>(
                  measureLst_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          measureLst_ = null;
        }
        return measureLstBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:message.PushBulkMeasureMessage)
    }

    static {
      defaultInstance = new PushBulkMeasureMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:message.PushBulkMeasureMessage)
  }

  public interface MeasureRecordOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string deviceAddr = 1;
    /**
     * <code>required string deviceAddr = 1;</code>
     */
    boolean hasDeviceAddr();
    /**
     * <code>required string deviceAddr = 1;</code>
     */
    java.lang.String getDeviceAddr();
    /**
     * <code>required string deviceAddr = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceAddrBytes();

    // required uint64 time = 2;
    /**
     * <code>required uint64 time = 2;</code>
     */
    boolean hasTime();
    /**
     * <code>required uint64 time = 2;</code>
     */
    long getTime();

    // required double distance = 3;
    /**
     * <code>required double distance = 3;</code>
     */
    boolean hasDistance();
    /**
     * <code>required double distance = 3;</code>
     */
    double getDistance();
  }
  /**
   * Protobuf type {@code message.MeasureRecord}
   */
  public static final class MeasureRecord extends
      com.google.protobuf.GeneratedMessage
      implements MeasureRecordOrBuilder {
    // Use MeasureRecord.newBuilder() to construct.
    private MeasureRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MeasureRecord(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MeasureRecord defaultInstance;
    public static MeasureRecord getDefaultInstance() {
      return defaultInstance;
    }

    public MeasureRecord getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MeasureRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              deviceAddr_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              time_ = input.readUInt64();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              distance_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.laser.message.PushBulkMeasureMessageFactory.internal_static_message_MeasureRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.laser.message.PushBulkMeasureMessageFactory.internal_static_message_MeasureRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.class, com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.Builder.class);
    }

    public static com.google.protobuf.Parser<MeasureRecord> PARSER =
        new com.google.protobuf.AbstractParser<MeasureRecord>() {
      public MeasureRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MeasureRecord(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MeasureRecord> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string deviceAddr = 1;
    public static final int DEVICEADDR_FIELD_NUMBER = 1;
    private java.lang.Object deviceAddr_;
    /**
     * <code>required string deviceAddr = 1;</code>
     */
    public boolean hasDeviceAddr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string deviceAddr = 1;</code>
     */
    public java.lang.String getDeviceAddr() {
      java.lang.Object ref = deviceAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceAddr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string deviceAddr = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceAddrBytes() {
      java.lang.Object ref = deviceAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint64 time = 2;
    public static final int TIME_FIELD_NUMBER = 2;
    private long time_;
    /**
     * <code>required uint64 time = 2;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 time = 2;</code>
     */
    public long getTime() {
      return time_;
    }

    // required double distance = 3;
    public static final int DISTANCE_FIELD_NUMBER = 3;
    private double distance_;
    /**
     * <code>required double distance = 3;</code>
     */
    public boolean hasDistance() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double distance = 3;</code>
     */
    public double getDistance() {
      return distance_;
    }

    private void initFields() {
      deviceAddr_ = "";
      time_ = 0L;
      distance_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDeviceAddr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDistance()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeviceAddrBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, distance_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeviceAddrBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, distance_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.MeasureRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.laser.message.PushBulkMeasureMessageFactory.internal_static_message_MeasureRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.laser.message.PushBulkMeasureMessageFactory.internal_static_message_MeasureRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.class, com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.Builder.class);
      }

      // Construct using com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceAddr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        distance_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.laser.message.PushBulkMeasureMessageFactory.internal_static_message_MeasureRecord_descriptor;
      }

      public com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord getDefaultInstanceForType() {
        return com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.getDefaultInstance();
      }

      public com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord build() {
        com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord buildPartial() {
        com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord result = new com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceAddr_ = deviceAddr_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.distance_ = distance_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord) {
          return mergeFrom((com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord other) {
        if (other == com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord.getDefaultInstance()) return this;
        if (other.hasDeviceAddr()) {
          bitField0_ |= 0x00000001;
          deviceAddr_ = other.deviceAddr_;
          onChanged();
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasDistance()) {
          setDistance(other.getDistance());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeviceAddr()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        if (!hasDistance()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.laser.message.PushBulkMeasureMessageFactory.MeasureRecord) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string deviceAddr = 1;
      private java.lang.Object deviceAddr_ = "";
      /**
       * <code>required string deviceAddr = 1;</code>
       */
      public boolean hasDeviceAddr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string deviceAddr = 1;</code>
       */
      public java.lang.String getDeviceAddr() {
        java.lang.Object ref = deviceAddr_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceAddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string deviceAddr = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceAddrBytes() {
        java.lang.Object ref = deviceAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string deviceAddr = 1;</code>
       */
      public Builder setDeviceAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceAddr = 1;</code>
       */
      public Builder clearDeviceAddr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceAddr_ = getDefaultInstance().getDeviceAddr();
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceAddr = 1;</code>
       */
      public Builder setDeviceAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceAddr_ = value;
        onChanged();
        return this;
      }

      // required uint64 time = 2;
      private long time_ ;
      /**
       * <code>required uint64 time = 2;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 time = 2;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>required uint64 time = 2;</code>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 time = 2;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0L;
        onChanged();
        return this;
      }

      // required double distance = 3;
      private double distance_ ;
      /**
       * <code>required double distance = 3;</code>
       */
      public boolean hasDistance() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double distance = 3;</code>
       */
      public double getDistance() {
        return distance_;
      }
      /**
       * <code>required double distance = 3;</code>
       */
      public Builder setDistance(double value) {
        bitField0_ |= 0x00000004;
        distance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double distance = 3;</code>
       */
      public Builder clearDistance() {
        bitField0_ = (bitField0_ & ~0x00000004);
        distance_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:message.MeasureRecord)
    }

    static {
      defaultInstance = new MeasureRecord(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:message.MeasureRecord)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_message_PushBulkMeasureMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_PushBulkMeasureMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_message_MeasureRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_MeasureRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034PushBulkMeasureMessage.proto\022\007message\"" +
      "D\n\026PushBulkMeasureMessage\022*\n\nmeasureLst\030" +
      "\001 \003(\0132\026.message.MeasureRecord\"C\n\rMeasure" +
      "Record\022\022\n\ndeviceAddr\030\001 \002(\t\022\014\n\004time\030\002 \002(\004" +
      "\022\020\n\010distance\030\003 \002(\001B:\n\031com.example.laser." +
      "messageB\035PushBulkMeasureMessageFactory"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_message_PushBulkMeasureMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_message_PushBulkMeasureMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_message_PushBulkMeasureMessage_descriptor,
              new java.lang.String[] { "MeasureLst", });
          internal_static_message_MeasureRecord_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_message_MeasureRecord_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_message_MeasureRecord_descriptor,
              new java.lang.String[] { "DeviceAddr", "Time", "Distance", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
